/* learn/learn_data/python/course.js
 * Course metadata + lesson index. Lesson content
 * (intro/task/hint/starter/answer/expectedOutput/testInputs) lives in
 * lessons/*.js and is loaded by loadLesson() on demand.
 *
 * Edit lesson files directly — keep title/chapter in this index in sync. */

LEARN.course('python', {
  slug: 'python',
  type: 'python',
  title: {"zh":"Python 基础语法","en":"Python · Core Syntax"},
  desc:  {"zh":"早期测试，可能包含大量未知错误。左侧课程内容可能不完善。","en":"Early access. May contain many unknown bugs. Course content on the left may be incomplete."},

  hasPlayground: true,
  playgroundTitle:  {"zh":"自定义 Python 代码","en":"Python Playground"},

  lessons: [
    { id:  1, section: 'main', slug: 'hello-python',
      title:   {"zh":"你好，Python！","en":"Hello, Python!"},
      chapter: {"zh":"Part 1 · print 与 input","en":"Part 1 · print & input"},
      file: 'lessons/01-hello-python.js' },
    { id:  2, section: 'main', slug: 'multiple-values-sep-end',
      title:   {"zh":"多值输出与 sep / end","en":"Multiple Values & sep / end"},
      chapter: {"zh":"Part 1 · print 与 input","en":"Part 1 · print & input"},
      file: 'lessons/02-multiple-values-sep-end.js' },
    { id:  3, section: 'main', slug: 'reading-user-input',
      title:   {"zh":"读取用户输入","en":"Reading User Input"},
      chapter: {"zh":"Part 1 · print 与 input","en":"Part 1 · print & input"},
      file: 'lessons/03-reading-user-input.js' },
    { id:  4, section: 'main', slug: 'arithmetic-operators',
      title:   {"zh":"算术运算符","en":"Arithmetic Operators"},
      chapter: {"zh":"Part 2 · 数值运算","en":"Part 2 · Numeric Ops"},
      file: 'lessons/04-arithmetic-operators.js' },
    { id:  5, section: 'main', slug: 'variables-expressions',
      title:   {"zh":"变量与表达式","en":"Variables & Expressions"},
      chapter: {"zh":"Part 2 · 数值运算","en":"Part 2 · Numeric Ops"},
      file: 'lessons/05-variables-expressions.js' },
    { id:  6, section: 'main', slug: 'string-to-number',
      title:   {"zh":"字符串转数字","en":"String to Number"},
      chapter: {"zh":"Part 3 · 类型转换","en":"Part 3 · Type Conversion"},
      file: 'lessons/06-string-to-number.js' },
    { id:  7, section: 'main', slug: 'number-to-string',
      title:   {"zh":"数字转字符串","en":"Number to String"},
      chapter: {"zh":"Part 3 · 类型转换","en":"Part 3 · Type Conversion"},
      file: 'lessons/07-number-to-string.js' },
    { id:  8, section: 'main', slug: 'floor-division',
      title:   {"zh":"整除","en":"Floor Division"},
      chapter: {"zh":"Part 4 · 整除与取余","en":"Part 4 · Floor Division & Modulo"},
      file: 'lessons/08-floor-division.js' },
    { id:  9, section: 'main', slug: 'modulo-time-conversion',
      title:   {"zh":"取余 % 与时间换算","en":"Modulo % & Time Conversion"},
      chapter: {"zh":"Part 4 · 整除与取余","en":"Part 4 · Floor Division & Modulo"},
      file: 'lessons/09-modulo-time-conversion.js' },
    { id: 10, section: 'main', slug: 'string-indexing',
      title:   {"zh":"字符串索引","en":"String Indexing"},
      chapter: {"zh":"Part 5 · 字符串索引与切片","en":"Part 5 · String Indexing & Slicing"},
      file: 'lessons/10-string-indexing.js' },
    { id: 11, section: 'main', slug: 'string-slicing',
      title:   {"zh":"字符串切片","en":"String Slicing"},
      chapter: {"zh":"Part 5 · 字符串索引与切片","en":"Part 5 · String Indexing & Slicing"},
      file: 'lessons/11-string-slicing.js' },
    { id: 12, section: 'main', slug: 'case-strip',
      title:   {"zh":"大小写与去空白","en":"Case & Strip"},
      chapter: {"zh":"Part 6 · 字符串方法","en":"Part 6 · String Methods"},
      file: 'lessons/12-case-strip.js' },
    { id: 13, section: 'main', slug: 'split-join',
      title:   {"zh":"split() 与 join()","en":"split() & join()"},
      chapter: {"zh":"Part 6 · 字符串方法","en":"Part 6 · String Methods"},
      file: 'lessons/13-split-join.js' },
    { id: 14, section: 'main', slug: 'f-string-basics',
      title:   {"zh":"f-string 基础","en":"f-string Basics"},
      chapter: {"zh":"Part 7 · f-string 格式化","en":"Part 7 · f-string Formatting"},
      file: 'lessons/14-f-string-basics.js' },
    { id: 15, section: 'main', slug: 'f-string-format-specs',
      title:   {"zh":"f-string 格式规范","en":"f-string Format Specs"},
      chapter: {"zh":"Part 7 · f-string 格式化","en":"Part 7 · f-string Formatting"},
      file: 'lessons/15-f-string-format-specs.js' },
    { id: 16, section: 'main', slug: 'list-basics',
      title:   {"zh":"列表基础","en":"List Basics"},
      chapter: {"zh":"Part 8 · 列表与元组","en":"Part 8 · Lists & Tuples"},
      file: 'lessons/16-list-basics.js' },
    { id: 17, section: 'main', slug: 'list-mutation-append',
      title:   {"zh":"列表修改与 append()","en":"List Mutation & append()"},
      chapter: {"zh":"Part 8 · 列表与元组","en":"Part 8 · Lists & Tuples"},
      file: 'lessons/17-list-mutation-append.js' },
    { id: 18, section: 'main', slug: 'tuples',
      title:   {"zh":"元组 tuple","en":"Tuples"},
      chapter: {"zh":"Part 8 · 列表与元组","en":"Part 8 · Lists & Tuples"},
      file: 'lessons/18-tuples.js' },
    { id: 19, section: 'main', slug: 'conditionals-1',
      title:   {"zh":"条件判断 1","en":"Conditionals 1"},
      chapter: {"zh":"Part 9 · 条件语句","en":"Part 9 · Conditionals"},
      file: 'lessons/19-conditionals-1.js' },
    { id: 20, section: 'main', slug: 'conditionals-2',
      title:   {"zh":"条件判断 2","en":"Conditionals 2"},
      chapter: {"zh":"Part 9 · 条件语句","en":"Part 9 · Conditionals"},
      file: 'lessons/20-conditionals-2.js' },
    { id: 21, section: 'main', slug: 'and-or-in',
      title:   {"zh":"and、or 和 in","en":"and, or & in"},
      chapter: {"zh":"Part 9 · 条件语句","en":"Part 9 · Conditionals"},
      file: 'lessons/21-and-or-in.js' },
    { id: 22, section: 'main', slug: 'chained-comparisons-not-in',
      title:   {"zh":"链式比较与 not in","en":"Chained Comparisons & not in"},
      chapter: {"zh":"Part 10 · 比较与成员运算符","en":"Part 10 · Comparisons & Membership"},
      file: 'lessons/22-chained-comparisons-not-in.js' },
    { id: 23, section: 'main', slug: 'def-return',
      title:   {"zh":"def 与 return","en":"def & return"},
      chapter: {"zh":"Part 11 · 函数定义","en":"Part 11 · Functions"},
      file: 'lessons/23-def-return.js' },
    { id: 24, section: 'main', slug: 'default-parameters',
      title:   {"zh":"默认参数","en":"Default Parameters"},
      chapter: {"zh":"Part 11 · 函数定义","en":"Part 11 · Functions"},
      file: 'lessons/24-default-parameters.js' },
    { id: 25, section: 'main', slug: 'boolean-return-values',
      title:   {"zh":"布尔返回值","en":"Boolean Return Values"},
      chapter: {"zh":"Part 11 · 函数定义","en":"Part 11 · Functions"},
      file: 'lessons/25-boolean-return-values.js' },
    { id: 26, section: 'main', slug: 'while-basics',
      title:   {"zh":"while 基础","en":"while Basics"},
      chapter: {"zh":"Part 12 · while 循环","en":"Part 12 · while Loop"},
      file: 'lessons/26-while-basics.js' },
    { id: 27, section: 'main', slug: 'while-accumulator',
      title:   {"zh":"while 累加器","en":"while Accumulator"},
      chapter: {"zh":"Part 12 · while 循环","en":"Part 12 · while Loop"},
      file: 'lessons/27-while-accumulator.js' },
    { id: 28, section: 'main', slug: 'for-range',
      title:   {"zh":"for 与 range()","en":"for & range()"},
      chapter: {"zh":"Part 13 · for 循环与 range()","en":"Part 13 · for Loop & range()"},
      file: 'lessons/28-for-range.js' },
    { id: 29, section: 'main', slug: 'for-over-a-list-accumulate',
      title:   {"zh":"for 遍历列表，累加","en":"for Over a List, Accumulate"},
      chapter: {"zh":"Part 13 · for 循环与 range()","en":"Part 13 · for Loop & range()"},
      file: 'lessons/29-for-over-a-list-accumulate.js' },
    { id: 30, section: 'main', slug: 'nested-loops-star-pattern',
      title:   {"zh":"嵌套循环与星形图案","en":"Nested Loops & Star Pattern"},
      chapter: {"zh":"Part 14 · 嵌套循环","en":"Part 14 · Nested Loops"},
      file: 'lessons/30-nested-loops-star-pattern.js' },
    { id: 31, section: 'main', slug: 'nested-loop-accumulation',
      title:   {"zh":"嵌套循环累加","en":"Nested Loop Accumulation"},
      chapter: {"zh":"Part 14 · 嵌套循环","en":"Part 14 · Nested Loops"},
      file: 'lessons/31-nested-loop-accumulation.js' },
    { id: 32, section: 'main', slug: 'dict-basics-create-lookup',
      title:   {"zh":"字典基础：创建与查找","en":"Dict Basics: Create & Lookup"},
      chapter: {"zh":"Part 15 · 字典 dict","en":"Part 15 · Dictionaries"},
      file: 'lessons/32-dict-basics-create-lookup.js' },
    { id: 33, section: 'main', slug: 'dict-modification-iteration',
      title:   {"zh":"字典修改与遍历","en":"Dict Modification & Iteration"},
      chapter: {"zh":"Part 15 · 字典 dict","en":"Part 15 · Dictionaries"},
      file: 'lessons/33-dict-modification-iteration.js' },
    { id: 34, section: 'main', slug: 'dict-word-frequency',
      title:   {"zh":"字典统计词频","en":"Dict Word Frequency"},
      chapter: {"zh":"Part 15 · 字典 dict","en":"Part 15 · Dictionaries"},
      file: 'lessons/34-dict-word-frequency.js' },
    { id: 35, section: 'main', slug: 'set-deduplication-membership',
      title:   {"zh":"集合去重与成员检查","en":"Set Deduplication & Membership"},
      chapter: {"zh":"Part 16 · 集合 set","en":"Part 16 · Sets"},
      file: 'lessons/35-set-deduplication-membership.js' },
    { id: 36, section: 'main', slug: 'set-operations',
      title:   {"zh":"集合运算","en":"Set Operations"},
      chapter: {"zh":"Part 16 · 集合 set","en":"Part 16 · Sets"},
      file: 'lessons/36-set-operations.js' },
    { id: 37, section: 'main', slug: 'alias-trap-copy',
      title:   {"zh":"别名陷阱与 copy()","en":"Alias Trap & copy()"},
      chapter: {"zh":"Part 17 · 列表可变性与复制","en":"Part 17 · List Mutability & Copying"},
      file: 'lessons/37-alias-trap-copy.js' },
    { id: 38, section: 'main', slug: 'enumerate-index-value-together',
      title:   {"zh":"enumerate() 同时取索引和值","en":"enumerate(): Index & Value Together"},
      chapter: {"zh":"Part 18 · 高级列表操作","en":"Part 18 · Advanced List Ops"},
      file: 'lessons/38-enumerate-index-value-together.js' },
    { id: 39, section: 'main', slug: 'sorted-with-a-key',
      title:   {"zh":"sorted() 与 key 参数","en":"sorted() with a key"},
      chapter: {"zh":"Part 18 · 高级列表操作","en":"Part 18 · Advanced List Ops"},
      file: 'lessons/39-sorted-with-a-key.js' },
    { id: 40, section: 'main', slug: 'lambda-as-a-sort-key',
      title:   {"zh":"lambda 作为排序键","en":"lambda as a Sort Key"},
      chapter: {"zh":"Part 18 · 高级列表操作","en":"Part 18 · Advanced List Ops"},
      file: 'lessons/40-lambda-as-a-sort-key.js' },
    { id: 41, section: 'main', slug: 'none-return-multiple-return-values',
      title:   {"zh":"None 返回值与多返回值","en":"None Return & Multiple Return Values"},
      chapter: {"zh":"Part 19 · 高级函数","en":"Part 19 · Advanced Functions"},
      file: 'lessons/41-none-return-multiple-return-values.js' },
    { id: 42, section: 'main', slug: 'early-return',
      title:   {"zh":"提前返回","en":"Early Return"},
      chapter: {"zh":"Part 19 · 高级函数","en":"Part 19 · Advanced Functions"},
      file: 'lessons/42-early-return.js' },
    { id: 43, section: 'main', slug: 'list-comprehension-basics',
      title:   {"zh":"列表推导式基础","en":"List Comprehension Basics"},
      chapter: {"zh":"Part 20 · 列表推导式","en":"Part 20 · List Comprehensions"},
      file: 'lessons/43-list-comprehension-basics.js' },
    { id: 44, section: 'main', slug: 'comprehension-with-filter',
      title:   {"zh":"带条件过滤的推导式","en":"Comprehension with Filter"},
      chapter: {"zh":"Part 20 · 列表推导式","en":"Part 20 · List Comprehensions"},
      file: 'lessons/44-comprehension-with-filter.js' },
    { id: 45, section: 'main', slug: 'comprehension-on-strings',
      title:   {"zh":"推导式处理字符串","en":"Comprehension on Strings"},
      chapter: {"zh":"Part 20 · 列表推导式","en":"Part 20 · List Comprehensions"},
      file: 'lessons/45-comprehension-on-strings.js' },
    { id: 46, section: 'main', slug: 'the-math-module',
      title:   {"zh":"math 模块","en":"The math Module"},
      chapter: {"zh":"Part 21 · 常用标准库","en":"Part 21 · Standard Library"},
      file: 'lessons/46-the-math-module.js' },
    { id: 47, section: 'main', slug: 'the-random-module',
      title:   {"zh":"random 模块","en":"The random Module"},
      chapter: {"zh":"Part 21 · 常用标准库","en":"Part 21 · Standard Library"},
      file: 'lessons/47-the-random-module.js' },
    { id: 48, section: 'main', slug: 'line-by-line-text-processing',
      title:   {"zh":"逐行处理文本（字符串模拟）","en":"Line-by-Line Text Processing"},
      chapter: {"zh":"Part 22 · 文件读写","en":"Part 22 · File I/O"},
      file: 'lessons/48-line-by-line-text-processing.js' },
    { id: 49, section: 'main', slug: 'parsing-a-csv-string',
      title:   {"zh":"解析 CSV 字符串","en":"Parsing a CSV String"},
      chapter: {"zh":"Part 23 · CSV 文件处理","en":"Part 23 · CSV Processing"},
      file: 'lessons/49-parsing-a-csv-string.js' },
    { id: 50, section: 'main', slug: 'try-and-except',
      title:   {"zh":"try 和 except","en":"try and except"},
      chapter: {"zh":"Part 24 · 异常处理","en":"Part 24 · Exception Handling"},
      file: 'lessons/50-try-and-except.js' },
    { id: 51, section: 'main', slug: 'multiple-except-clauses',
      title:   {"zh":"捕获多种异常","en":"Multiple except Clauses"},
      chapter: {"zh":"Part 24 · 异常处理","en":"Part 24 · Exception Handling"},
      file: 'lessons/51-multiple-except-clauses.js' },
    { id: 52, section: 'main', slug: 'raise-throwing-exceptions',
      title:   {"zh":"raise 主动抛出异常","en":"raise: Throwing Exceptions"},
      chapter: {"zh":"Part 24 · 异常处理","en":"Part 24 · Exception Handling"},
      file: 'lessons/52-raise-throwing-exceptions.js' },
    { id: 53, section: 'main', slug: 'recursion-factorial',
      title:   {"zh":"递归：阶乘","en":"Recursion: Factorial"},
      chapter: {"zh":"Part 25 · 递归","en":"Part 25 · Recursion"},
      file: 'lessons/53-recursion-factorial.js' },
    { id: 54, section: 'main', slug: 'recursion-fibonacci',
      title:   {"zh":"递归：斐波那契数列","en":"Recursion: Fibonacci"},
      chapter: {"zh":"Part 25 · 递归","en":"Part 25 · Recursion"},
      file: 'lessons/54-recursion-fibonacci.js' },
    { id: 55, section: 'main', slug: 'recursion-list-max',
      title:   {"zh":"递归：列表求最大值","en":"Recursion: List Max"},
      chapter: {"zh":"Part 25 · 递归","en":"Part 25 · Recursion"},
      file: 'lessons/55-recursion-list-max.js' },
    { id: 56, section: 'main', slug: 'find-fix-the-bug',
      title:   {"zh":"找出并修复 Bug","en":"Find & Fix the Bug"},
      chapter: {"zh":"Part 26 · 调试技巧","en":"Part 26 · Debugging"},
      file: 'lessons/56-find-fix-the-bug.js' },
    { id: 57, section: 'main', slug: 'zip-parallel-iteration-unpacking',
      title:   {"zh":"zip() 并行遍历与解包","en":"zip() Parallel Iteration & Unpacking"},
      chapter: {"zh":"Part 27 · 实用技巧","en":"Part 27 · Practical Tips"},
      file: 'lessons/57-zip-parallel-iteration-unpacking.js' },
    { id: 58, section: 'main', slug: 'any-and-all',
      title:   {"zh":"any() 与 all()","en":"any() and all()"},
      chapter: {"zh":"Part 27 · 实用技巧","en":"Part 27 · Practical Tips"},
      file: 'lessons/58-any-and-all.js' },
    { id: 59, section: 'final', slug: 'caesar-cipher-encrypt-decrypt',
      title:   {"zh":"凯撒密码：加密与解密","en":"Caesar Cipher: Encrypt & Decrypt"},
      chapter: {"zh":"综合挑战","en":"Comprehensive Challenges"},
      file: 'lessons/59-caesar-cipher-encrypt-decrypt.js' },
    { id: 60, section: 'final', slug: 'matrix-multiplication',
      title:   {"zh":"矩阵乘法","en":"Matrix Multiplication"},
      chapter: {"zh":"综合挑战","en":"Comprehensive Challenges"},
      file: 'lessons/60-matrix-multiplication.js' },
    { id: 61, section: 'final', slug: 'merge-sort',
      title:   {"zh":"归并排序","en":"Merge Sort"},
      chapter: {"zh":"综合挑战","en":"Comprehensive Challenges"},
      file: 'lessons/61-merge-sort.js' },
    { id: 62, section: 'final', slug: 'binary-search-exception-handling',
      title:   {"zh":"二分查找 + 异常处理","en":"Binary Search + Exception Handling"},
      chapter: {"zh":"综合挑战","en":"Comprehensive Challenges"},
      file: 'lessons/62-binary-search-exception-handling.js' },
    { id: 63, section: 'final', slug: 'anagrams',
      title:   {"zh":"字谜","en":"Anagrams"},
      chapter: {"zh":"综合挑战","en":"Comprehensive Challenges"},
      file: 'lessons/63-anagrams.js' },
    { id: 64, section: 'final', slug: 'sudoku-validator',
      title:   {"zh":"Sudoku 验证器","en":"Sudoku Validator"},
      chapter: {"zh":"Boss关","en":"Boss Level"},
      file: 'lessons/64-sudoku-validator.js' },
    { id: 65, section: 'final', slug: 'library-management-system',
      title:   {"zh":"图书馆管理系统","en":"Library Management System"},
      chapter: {"zh":"Boss关","en":"Boss Level"},
      file: 'lessons/65-library-management-system.js' },
    { id: 66, section: 'final', slug: 'vigenere-cipher-frequency-analysis',
      title:   {"zh":"维吉尼亚密码 + 频率分析","en":"Vigenere Cipher + Frequency Analysis"},
      chapter: {"zh":"Boss关","en":"Boss Level"},
      file: 'lessons/66-vigenere-cipher-frequency-analysis.js' },
    { id: 67, section: 'final', slug: 'student-records-manager',
      title:   {"zh":"学生档案管理系统","en":"Student Records Manager"},
      chapter: {"zh":"Boss关","en":"Boss Level"},
      file: 'lessons/67-student-records-manager.js' },
    { id: 68, section: 'final', slug: 'sales-data',
      title:   {"zh":"销售数据","en":"Sales Data"},
      chapter: {"zh":"Boss关","en":"Boss Level"},
      file: 'lessons/68-sales-data.js' },
  ],
});
