/* learn/learn_data/sql/course.js
 * Course metadata + lesson index + schema manifest. Lesson content
 * (intro/task/hint/setup/expectedSql/...) lives in lessons/*.js, loaded by
 * loadLesson() on demand. Schemas in schemas/*.js, loaded by loadSchema()
 * the first time a lesson or the playground references them.
 *
 * Edit lesson files directly — keep title/chapter in this index in sync. */

LEARN.course('sql', {
  slug: 'sql',
  type: 'sql',
  title: {"zh":"SQL 基本语法","en":"SQL · Core Syntax"},
  desc:  {"zh":"学习 SQL 的基本查询语句","en":"Learn the fundamentals of SQL queries"},

  hasPlayground: true,
  playgroundTitle:  {"zh":"自定义 SQL 语句","en":"Custom SQL Playground"},
  playgroundSchema: 'final_schema',

  schemas: {
    c1_schema: 'schemas/c1_schema.js',
    c2_schema: 'schemas/c2_schema.js',
    c3_schema: 'schemas/c3_schema.js',
    c4_schema: 'schemas/c4_schema.js',
    c6_schema: 'schemas/c6_schema.js',
    c7_schema: 'schemas/c7_schema.js',
    c8_schema: 'schemas/c8_schema.js',
    c9_schema: 'schemas/c9_schema.js',
    c10_schema: 'schemas/c10_schema.js',
    c11_schema: 'schemas/c11_schema.js',
    c12_schema: 'schemas/c12_schema.js',
    c13_schema: 'schemas/c13_schema.js',
    c14_schema: 'schemas/c14_schema.js',
    c15_schema: 'schemas/c15_schema.js',
    c16_schema: 'schemas/c16_schema.js',
    c17_schema: 'schemas/c17_schema.js',
    c18_schema: 'schemas/c18_schema.js',
    c20_schema: 'schemas/c20_schema.js',
    c23_schema: 'schemas/c23_schema.js',
    c24_schema: 'schemas/c24_schema.js',
    c25_schema: 'schemas/c25_schema.js',
    c26_schema: 'schemas/c26_schema.js',
    c27_schema: 'schemas/c27_schema.js',
    c28_schema: 'schemas/c28_schema.js',
    c29_schema: 'schemas/c29_schema.js',
    c30_schema: 'schemas/c30_schema.js',
    c31_schema: 'schemas/c31_schema.js',
    c32_schema: 'schemas/c32_schema.js',
    final_schema: 'schemas/final_schema.js',
  },

  lessons: [
    { id:  1, section: 'main', slug: 'select-basics',
      title:   {"zh":"Part 1 · SELECT —— 选哪些列","en":"Part 1 · SELECT — pick the columns"},
      chapter: {"zh":"SQL 语法大全 · Part 1","en":"SQL syntax guide · Part 1"},
      file: 'lessons/01-select-basics.js' },
    { id:  2, section: 'main', slug: 'from-tables',
      title:   {"zh":"Part 2 · FROM —— 从哪张表","en":"Part 2 · FROM — pick the table"},
      chapter: {"zh":"SQL 语法大全 · Part 2","en":"SQL syntax guide · Part 2"},
      file: 'lessons/02-from-tables.js' },
    { id:  3, section: 'main', slug: 'where-filter',
      title:   {"zh":"Part 3 · WHERE —— 筛选行","en":"Part 3 · WHERE — filter rows"},
      chapter: {"zh":"SQL 语法大全 · Part 3","en":"SQL syntax guide · Part 3"},
      file: 'lessons/03-where-filter.js' },
    { id:  4, section: 'main', slug: 'comparison-operators',
      title:   {"zh":"Part 4 · 比较运算符","en":"Part 4 · Comparison Operators"},
      chapter: {"zh":"SQL 语法大全 · Part 4","en":"SQL syntax guide · Part 4"},
      file: 'lessons/04-comparison-operators.js' },
    { id:  5, section: 'main', slug: 'and-or-not',
      title:   {"zh":"Part 5 · AND / OR / NOT","en":"Part 5 · AND / OR / NOT"},
      chapter: {"zh":"SQL 语法大全 · Part 5","en":"SQL syntax guide · Part 5"},
      file: 'lessons/05-and-or-not.js' },
    { id:  6, section: 'main', slug: 'in-list',
      title:   {"zh":"Part 6 · IN / NOT IN","en":"Part 6 · IN / NOT IN"},
      chapter: {"zh":"SQL 语法大全 · Part 6","en":"SQL syntax guide · Part 6"},
      file: 'lessons/06-in-list.js' },
    { id:  7, section: 'main', slug: 'between',
      title:   {"zh":"Part 7 · BETWEEN —— 范围筛选","en":"Part 7 · BETWEEN — range filter"},
      chapter: {"zh":"SQL 语法大全 · Part 7","en":"SQL syntax guide · Part 7"},
      file: 'lessons/07-between.js' },
    { id:  8, section: 'main', slug: 'like-pattern',
      title:   {"zh":"Part 8 · LIKE —— 字符串模糊匹配","en":"Part 8 · LIKE — pattern matching"},
      chapter: {"zh":"SQL 语法大全 · Part 8","en":"SQL syntax guide · Part 8"},
      file: 'lessons/08-like-pattern.js' },
    { id:  9, section: 'main', slug: 'is-null',
      title:   {"zh":"Part 9 · IS NULL —— 空值检查","en":"Part 9 · IS NULL — null check"},
      chapter: {"zh":"SQL 语法大全 · Part 9","en":"SQL syntax guide · Part 9"},
      file: 'lessons/09-is-null.js' },
    { id: 10, section: 'main', slug: 'order-by',
      title:   {"zh":"Part 10 · ORDER BY —— 排序","en":"Part 10 · ORDER BY — sorting"},
      chapter: {"zh":"SQL 语法大全 · Part 10","en":"SQL syntax guide · Part 10"},
      file: 'lessons/10-order-by.js' },
    { id: 11, section: 'main', slug: 'limit-offset',
      title:   {"zh":"Part 11 · LIMIT / OFFSET —— 限制行数","en":"Part 11 · LIMIT / OFFSET — page through rows"},
      chapter: {"zh":"SQL 语法大全 · Part 11","en":"SQL syntax guide · Part 11"},
      file: 'lessons/11-limit-offset.js' },
    { id: 12, section: 'main', slug: 'distinct',
      title:   {"zh":"Part 12 · DISTINCT —— 去重","en":"Part 12 · DISTINCT — unique values"},
      chapter: {"zh":"SQL 语法大全 · Part 12","en":"SQL syntax guide · Part 12"},
      file: 'lessons/12-distinct.js' },
    { id: 13, section: 'main', slug: 'alias-as',
      title:   {"zh":"Part 13 · AS —— 起别名","en":"Part 13 · AS — column aliases"},
      chapter: {"zh":"SQL 语法大全 · Part 13","en":"SQL syntax guide · Part 13"},
      file: 'lessons/13-alias-as.js' },
    { id: 14, section: 'main', slug: 'inner-join',
      title:   {"zh":"Part 14 · INNER JOIN —— 内连接","en":"Part 14 · INNER JOIN"},
      chapter: {"zh":"SQL 语法大全 · Part 14","en":"SQL syntax guide · Part 14"},
      file: 'lessons/14-inner-join.js' },
    { id: 15, section: 'main', slug: 'left-join',
      title:   {"zh":"Part 15 · LEFT JOIN —— 左连接","en":"Part 15 · LEFT JOIN"},
      chapter: {"zh":"SQL 语法大全 · Part 15","en":"SQL syntax guide · Part 15"},
      file: 'lessons/15-left-join.js' },
    { id: 16, section: 'main', slug: 'multi-join',
      title:   {"zh":"Part 16 · 多表连续 JOIN","en":"Part 16 · Chaining JOINs"},
      chapter: {"zh":"SQL 语法大全 · Part 16","en":"SQL syntax guide · Part 16"},
      file: 'lessons/16-multi-join.js' },
    { id: 17, section: 'main', slug: 'count',
      title:   {"zh":"Part 17 · COUNT —— 计数","en":"Part 17 · COUNT — counting rows"},
      chapter: {"zh":"SQL 语法大全 · Part 17","en":"SQL syntax guide · Part 17"},
      file: 'lessons/17-count.js' },
    { id: 18, section: 'main', slug: 'sum-avg-max-min',
      title:   {"zh":"Part 18 · SUM / AVG / MAX / MIN","en":"Part 18 · SUM / AVG / MAX / MIN"},
      chapter: {"zh":"SQL 语法大全 · Part 18","en":"SQL syntax guide · Part 18"},
      file: 'lessons/18-sum-avg-max-min.js' },
    { id: 19, section: 'main', slug: 'group-by',
      title:   {"zh":"Part 19 · GROUP BY —— 分组聚合","en":"Part 19 · GROUP BY — group + aggregate"},
      chapter: {"zh":"SQL 语法大全 · Part 19","en":"SQL syntax guide · Part 19"},
      file: 'lessons/19-group-by.js' },
    { id: 20, section: 'main', slug: 'having',
      title:   {"zh":"Part 20 · HAVING —— 分组后筛选","en":"Part 20 · HAVING — filter after grouping"},
      chapter: {"zh":"SQL 语法大全 · Part 20","en":"SQL syntax guide · Part 20"},
      file: 'lessons/20-having.js' },
    { id: 21, section: 'main', slug: 'subquery-where',
      title:   {"zh":"Part 21 · 子查询（WHERE 里）","en":"Part 21 · Subqueries in WHERE"},
      chapter: {"zh":"SQL 语法大全 · Part 21","en":"SQL syntax guide · Part 21"},
      file: 'lessons/21-subquery-where.js' },
    { id: 22, section: 'main', slug: 'subquery-from',
      title:   {"zh":"Part 22 · 子查询（FROM 里 —— 派生表）","en":"Part 22 · Subqueries in FROM (derived tables)"},
      chapter: {"zh":"SQL 语法大全 · Part 22","en":"SQL syntax guide · Part 22"},
      file: 'lessons/22-subquery-from.js' },
    { id: 23, section: 'main', slug: 'exists',
      title:   {"zh":"Part 23 · EXISTS / NOT EXISTS","en":"Part 23 · EXISTS / NOT EXISTS"},
      chapter: {"zh":"SQL 语法大全 · Part 23","en":"SQL syntax guide · Part 23"},
      file: 'lessons/23-exists.js' },
    { id: 24, section: 'main', slug: 'coalesce',
      title:   {"zh":"Part 24 · COALESCE —— 替换 NULL","en":"Part 24 · COALESCE — replace NULL"},
      chapter: {"zh":"SQL 语法大全 · Part 24","en":"SQL syntax guide · Part 24"},
      file: 'lessons/24-coalesce.js' },
    { id: 25, section: 'main', slug: 'case-when',
      title:   {"zh":"Part 25 · CASE WHEN —— SQL 的 if-else","en":"Part 25 · CASE WHEN — SQL's if-else"},
      chapter: {"zh":"SQL 语法大全 · Part 25","en":"SQL syntax guide · Part 25"},
      file: 'lessons/25-case-when.js' },
    { id: 26, section: 'main', slug: 'execution-order',
      title:   {"zh":"Part 26 · SQL 执行顺序（必背）","en":"Part 26 · Logical execution order (memorize)"},
      chapter: {"zh":"SQL 语法大全 · Part 26","en":"SQL syntax guide · Part 26"},
      file: 'lessons/26-execution-order.js' },
    { id: 27, section: 'main', slug: 'practical-find-duplicates',
      title:   {"zh":"Part 27.1 · 找重复的行","en":"Part 27.1 · Find duplicate rows"},
      chapter: {"zh":"SQL 语法大全 · Part 27.1","en":"SQL syntax guide · Part 27.1"},
      file: 'lessons/27-practical-find-duplicates.js' },
    { id: 28, section: 'main', slug: 'practical-top-n-ties',
      title:   {"zh":"Part 27.2 · 找前 N 名（带并列）","en":"Part 27.2 · Top N with ties"},
      chapter: {"zh":"SQL 语法大全 · Part 27.2","en":"SQL syntax guide · Part 27.2"},
      file: 'lessons/28-practical-top-n-ties.js' },
    { id: 29, section: 'main', slug: 'practical-per-group-max',
      title:   {"zh":"Part 27.3 · 每组里取最大那一行","en":"Part 27.3 · The max row in each group"},
      chapter: {"zh":"SQL 语法大全 · Part 27.3","en":"SQL syntax guide · Part 27.3"},
      file: 'lessons/29-practical-per-group-max.js' },
    { id: 30, section: 'main', slug: 'practical-percentage',
      title:   {"zh":"Part 27.4 · 算占比 / 累计百分比","en":"Part 27.4 · Percentage of total"},
      chapter: {"zh":"SQL 语法大全 · Part 27.4","en":"SQL syntax guide · Part 27.4"},
      file: 'lessons/30-practical-percentage.js' },
    { id: 31, section: 'main', slug: 'practical-nullif',
      title:   {"zh":"Part 27.7 · 防止除零（NULLIF）","en":"Part 27.7 · Avoid division by zero"},
      chapter: {"zh":"SQL 语法大全 · Part 27.7","en":"SQL syntax guide · Part 27.7"},
      file: 'lessons/31-practical-nullif.js' },
    { id: 32, section: 'main', slug: 'practical-nth-largest',
      title:   {"zh":"Part 27.9 · 取第 N 大的值","en":"Part 27.9 · The N-th largest value"},
      chapter: {"zh":"SQL 语法大全 · Part 27.9","en":"SQL syntax guide · Part 27.9"},
      file: 'lessons/32-practical-nth-largest.js' },
    { id: 33, section: 'final', slug: 'final-copies-per-branch',
      title:   {"zh":"挑战 1 · 每个分馆的藏书副本数（含 0）","en":"Challenge 1 · Copies per branch (including zero)"},
      chapter: {"zh":"综合挑战 · LEFT JOIN + GROUP BY","en":"Final challenge · LEFT JOIN + GROUP BY"},
      file: 'lessons/33-final-copies-per-branch.js' },
    { id: 34, section: 'final', slug: 'final-active-loan-no-membership',
      title:   {"zh":"挑战 2 · 在借书但没有有效会员","en":"Challenge 2 · Active loan, no active membership"},
      chapter: {"zh":"综合挑战 · NOT EXISTS / 双重否定","en":"Final challenge · NOT EXISTS"},
      file: 'lessons/34-final-active-loan-no-membership.js' },
    { id: 35, section: 'final', slug: 'final-genre-fans',
      title:   {"zh":"挑战 3 · 类型迷（同类型 &gt; 3 本）","en":"Challenge 3 · Genre fans (> 3 distinct books)"},
      chapter: {"zh":"综合挑战 · GROUP BY 多键 + HAVING","en":"Final challenge · GROUP BY multi-key + HAVING"},
      file: 'lessons/35-final-genre-fans.js' },
    { id: 36, section: 'final', slug: 'final-top-readers-ties',
      title:   {"zh":"挑战 4 · 阅读最多作者的前 3 名（含并列）","en":"Challenge 4 · Top 3 by distinct authors (with ties)"},
      chapter: {"zh":"综合挑战 · 含并列的 Top-N","en":"Final challenge · Top-N with ties"},
      file: 'lessons/36-final-top-readers-ties.js' },
    { id: 37, section: 'final', slug: 'final-per-branch-top-genre',
      title:   {"zh":"挑战 5 · 每个分馆借阅最多的类型","en":"Challenge 5 · Top-loaned genre per branch"},
      chapter: {"zh":"综合挑战 · 分组内最大值 + 含 0 + 并列","en":"Final challenge · per-group max + zeros + ties"},
      file: 'lessons/37-final-per-branch-top-genre.js' },
    { id: 38, section: 'final', slug: 'final-review-every-borrowed',
      title:   {"zh":"挑战 6 · 每借必评的读者","en":"Challenge 6 · Reviewed every book borrowed"},
      chapter: {"zh":"综合挑战 · 全称量词（双重否定）","en":"Final challenge · universal quantifier"},
      file: 'lessons/38-final-review-every-borrowed.js' },
    { id: 39, section: 'final', slug: 'final-avg-fine-per-loan',
      title:   {"zh":"挑战 7 · 每位会员每笔借阅的平均罚金","en":"Challenge 7 · Average fine per loan, per member"},
      chapter: {"zh":"综合挑战 · LEFT JOIN + COALESCE + CASE 防除零","en":"Final challenge · LEFT JOIN + COALESCE + safe division"},
      file: 'lessons/39-final-avg-fine-per-loan.js' },
    { id: 40, section: 'final', slug: 'final-popular-and-rated',
      title:   {"zh":"挑战 8 · 既受欢迎又口碑好的书","en":"Challenge 8 · Popular AND well-rated books"},
      chapter: {"zh":"综合挑战 · 标量子查询并列条件","en":"Final challenge · parallel scalar subqueries"},
      file: 'lessons/40-final-popular-and-rated.js' },
    { id: 41, section: 'final', slug: 'final-per-member-top-genre',
      title:   {"zh":"挑战 9 · 每位会员最常借阅的类型","en":"Challenge 9 · Each member's favourite genre"},
      chapter: {"zh":"综合挑战 · 分组内最大值 + 并列","en":"Final challenge · per-group max + ties"},
      file: 'lessons/41-final-per-member-top-genre.js' },
    { id: 42, section: 'final', slug: 'final-global-authors',
      title:   {"zh":"挑战 10 · 国际化的作者","en":"Challenge 10 · Authors with global reach"},
      chapter: {"zh":"综合挑战 · 跨 5 张表 + COUNT(DISTINCT)","en":"Final challenge · 5-table chain + COUNT(DISTINCT)"},
      file: 'lessons/42-final-global-authors.js' },
  ],
});
